### ISSUE TITLE
ascii to cwa file creation

### ISSUE THREAD

**Issue by rx96304** [Mirkes/AccelerometerCWA2BINConverter#1]
I use your **g.cwaread()** in GGIR package  to read the axivity file to a R dataframe.
Is there a way to write this R data frame back to a cwa file? Essentially I want to edit the data frame and resave it as a cwa file. 
Please let me know.
Krishna

**Comment by Mirkes** [comment]
Dear Krishna,

There is no such possibility now. Conversation from cwa format is non invertible because of correction of sampling frequency. Another reason is almost absence of software to work with this format.
Do you know about such tools for bin format? If yes then you can use my cwa-bin convertor and then work with bin files.
Of course, it is possible to develop function for writing of arbitrary dataframe into bin or cwa format but, as I know, this function is not necessary for most of researcher.

Best regards,
Evgeny

**Comment by rx96304** [comment]
Thank you for clarifying. 
I have a project need to create 25 CWA files for loading in to a database. One option is to buy the device for 25 users and collect 2-week data and then download the CWA file and store it in the database. Another option is use the g.cwaread() in GGIR package that you developed to open the file, mutate some data (like accelerometer x, y and z) and create 20 such clones and then save them back as CWA files (keeping the sampling frequency same in all). From your description above, I now realize that this route is unavailable. 
A alternative will be, I read the CWA file with g.cwaread(), mutate the data and may save the mutant(s) data frame  as a RDS file (binary) in a compressed state (I see that the file takes megabytes size as against Gigs in CWA file format) and then store in the database.

**Comment by Mirkes** [comment]
Really I cannot understand necessity to change x, y and z but if it is necessary…

Good luck!
Evgeny

**Comment by rx96304** [comment]
I need not change x, y, z. For the purpose of creating a new cwa file, I can change the header information alone. But the requirement is to write to a cwa file.

**Comment by Mirkes** [comment]
But you can download different cwa files and use it.
Really cwa format is not widely used. The main problem is slow reading in GGIR. I know that there is specially developed software for cwa files, may be it will be useful for you. You can find this software in Google.

Good luck!

**Comment by rx96304** [comment]
Can you point me to Biobank that houses different CWA files? I could not locate a downloadable repository. May be that will solve the need to have 20 or so CWA files.

Secondly on the "specially developed software for cwa files" - are you referring to OMGui? Right now I used g.cwaread() in R which is quite handy. 
Thanks for your time.

**Comment by Mirkes** [comment]
Yes I am refereeing for OMGui, MatLab, java and python versions of the same software. I cannot recommend this software because I do not try to use it for your purposes. May be you can use it.

**Comment by rx96304** [comment]
What are byte positions in the cwa file for the following which are not extracted by the g.cwaread()?
from the function g.extractheadervars = function(I) {
...........
...........
............

 else if (mon == "actigraph" | mon == "axivity") { #todo: create automatic extraction of information from actigraph fileheader 
33     id = "not extracted"	# volunteer ID as stored in binary file header 
34     iid = "not extracted" #investigator id 
35     HN = "not extracted" #handedness 
36     BL = "not extracted" #body location 
37     SX = "not extracted" #gender 
38     SN = "not extracted" #serial number 
39    		 
42     } 
43   } 
 
Thanks for your time

**Comment by Mirkes** [comment]
In accordance with official documentation  header of CWA file contains following information:
{
    uint16_t packetHeader;                      ///< @ 0  +2   ASCII "MD", little-endian (0x444D)
    uint16_t packetLength;                      ///< @ 2  +2   Packet length (1020 bytes, with header (4) = 1024 bytes total)
    uint8_t  reserved1;                         ///< @ 4  +1   (1 byte reserved)
    uint16_t deviceId;                          ///< @ 5  +2   Device identifier
    uint32_t sessionId;                         ///< @ 7  +4   Unique session identifier
    uint16_t reserved2;                         ///< @11  +2   (2 bytes reserved)
    cwa_timestamp_t loggingStartTime;           ///< @13  +4   Start time for delayed logging
    cwa_timestamp_t loggingEndTime;             ///< @17  +4   Stop time for delayed logging
    uint32_t loggingCapacity;                   ///< @21  +4   (Deprecated: preset maximum number of samples to collect, 0 = unlimited)
    uint8_t  reserved3[11];                     ///< @25  +11  (11 bytes reserved)
    uint8_t  samplingRate;                      ///< @36  +1   Sampling rate code, frequency (3200/(1<<(15-(rate & 0x0f)))) Hz, range (+/-g) (16 >> (rate >> 6)).
    cwa_timestamp_t lastChangeTime;             ///< @37  +4   Last change metadata time
    uint8_t  firmwareRevision;                  ///< @41  +1   Firmware revision number
    int16_t  timeZone;                          ///< @42  +2   (Unused: originally reserved for a "Time Zone offset from UTC in minutes", 0xffff = -1 = unknown)
    uint8_t  reserved4[20];                     ///< @44  +20  (20 bytes reserved)
    uint8_t  annotation[OM_METADATA_SIZE];      ///< @64  +448 Scratch buffer / meta-data (448 characters, ignore trailing 0x20/0x00/0xff bytes, url-encoded UTF-8 name-value pairs)
    uint8_t  reserved[512];                     ///< @512 +512 (Unused: originally reserved for post-collection scratch buffer / meta-data) (512 bytes)
} cwa_header_t;

You can see that there is no information which you mentioned exclude serial number. Serial number is written with name "Device Unique Serial Code:".
Scratch buffer can contains additional information but all CWA files which I saw have empty scratch buffer.

Sorry but I cannot extract information which is not included to file.

**Comment by rx96304** [comment]
Thank you Mirkes. 

I wonder why the fields in the device 
# volunteer ID  
 #investigator id
 #handedness
 #body location
 #gender

are not captured in the scratch buffer even though they are given as input boxes in the Ax3 Axivity wearable during configuration of the file. I have used the Axivity device myself and I can fill in those boxes during configuration but do not know how to extract those from the CWA file.

When I saw your cwa2bin.Java, I saw   
out.write("Trial Info"); 
272             out.newLine(); 
273             out.write("Study Centre:"); 
274             out.newLine(); 
275             out.write("Study Code:"); 
276             out.newLine(); 
277             out.write("Investigator ID:"); 
278             out.newLine(); 
279             out.write("Exercise Type:"); 
280             out.newLine(); 
281             out.write("Config Operator ID:"); 
282             out.newLine(); 
283             out.write("Config Time:" + timeStampFormat.format(dates.get(0))); 
284             out.newLine(); 
285             out.write("Config Notes:Note"); 
286             out.newLine(); 
287             out.write("Extract Operator ID:"); 

which seems to suggest that the code is able to read it out of the cwa file. Granted some of the biobank data did not have those fields filled in, **can your code pull them out if they (the fields as above) are filled?**. If so the code knows which byte positions in the CWA file they get stored isn't it?

I appreciate your time to clarify these doubts.

**Comment by Mirkes** [comment]
Dear Balagopalakrishna,

All listed fields are part of Bin file structure. Unfortunately I do not have exact description of BIN file format and decide to write empty values if I cannot extract values.
Could I ask you to send me the first 10 kilobytes of your cwa file? I’ll try to understand where information is stored.

Best regards,
Evgeny

**Comment by rx96304** [comment]
Thank you for your comments. I will generate the CWA file with the field updated and send it to you. I was asked by my team to wait for 2 weeks before the device becomes available as it is being currently worn by another user.

**Comment by rx96304** [comment]
I generated a cwa file (24 hours data, 100 KHz) sampling with all the fields as above populated. Can you use your code to extract the above fields? Thanks. I will send it by email.

**Comment by rx96304** [comment]
Did you get the zipped cwa file sent by email?

**Comment by Mirkes** [comment]
Dear Balagopalakrishna,

I did not receive any files from you.

Best regards,
Evgeny
